### ISSUE TITLE
After run this uninstaller, SQL Server Management Studio 16.5.3 is not working

### ISSUE THREAD

**Issue by heavenwing** [Microsoft/VisualStudioUninstaller#70]
SQL Server Management Studio 16 use Visual Studio 2015 Shell, and I found that uninstaller uninstall it .

**Comment by heavenwing** [comment]
I repaired it and re-installed it , it's not working yet.

**Comment by heaths** [comment]
VS powers SQL Management Studio so the initial break is expected since the uninstaller by design ignores any ref-counting, but repairing it should've worked. Please run http://aka.ms/collect.exe and attach %temp%\vslogs.zip to a new bug on http//connect.microsoft.com/visualstudio so we can troubleshoot further.

**Comment by ptzenos** [comment]
Try to also repair "Microsoft Visual Studio 2015 Shell (isolated)" through add/remove programs.

**Comment by heavenwing** [comment]
@heaths I dump log and created a bug in connect 
@ptzenos when I try to repair  "Microsoft Visual Studio 2015 Shell (isolated)", I get below error:
![image](https://cloud.githubusercontent.com/assets/2920062/23823213/ba692264-0698-11e7-8b96-ef045fe8d5d2.png)
and
![image](https://cloud.githubusercontent.com/assets/2920062/23823216/cc3e77aa-0698-11e7-8f50-f8ba30ff0474.png)
