### ISSUE TITLE
Feature request: Uninstalling specific version of VS

### ISSUE THREAD

**Issue by wmjordan** [Microsoft/VisualStudioUninstaller#91]
Currently I have a working VS 2017 and a broken VS 2015.
Is it possible to clean up the broken VS 2015 without touching the healthy VS 2017?

**Comment by shabtaisharon** [comment]
I have the same issue

**Comment by dreamer1031** [comment]
I have the same issue too! Did you solve this problem?

**Comment by heaths** [comment]
There are a lot of shared products installed by either. This project has not been updated for VS2017 nor do we have any plans to (the VS2017 (un)installer is a complete rewrite with more fixes for common issues during uninstall and other operations), so it should not remove VS2017 but will remove packages shared from VS2015 for VS2017. After uninstalling VS2015, just repair VS2017 and you should be fine. If not, please use the Feedback icon in Visual Studio or the Visual Studio Installer to report an issue since it will collect necessary logs.
